#!/bin/sh
set -e
cd "$(dirname "$0")"

download() {
  file="$1"
  query="$2"
  url="https://source.unsplash.com/1200x800/?${query},food"
  echo "downloading $file"
  curl -L --silent --show-error "$url" -o "$file"
}

download papas-fritas.jpg "french-fries"
download bruschettas.jpg "bruschetta"
download nachos.jpg "nachos"
download aros-cebolla.jpg "onion-rings"
download empanadas.jpg "empanadas"
download provoleta.jpg "provolone-cheese"
download rabas.jpg "fried-calamari"
download tabla-fiambres.jpg "charcuterie-board"
download bastones-mozzarella.jpg "mozzarella-sticks"
download nuggets.jpg "chicken-nuggets"

download hamburguesa.jpg "burger"
download pizza.jpg "pizza"
download carne.jpg "grilled-steak"
download milanesa.jpg "breaded-cutlet"
download pasta.jpg "pasta-dish"
download ensalada-caesar.jpg "caesar-salad"
download sushi.jpg "sushi-rolls"
download lomito.jpg "steak-sandwich"
download pollo-grillado.jpg "grilled-chicken"
download tacos.jpg "tacos"

download coca-cola.jpg "coca-cola"
download sprite.jpg "lemon-lime-soda"
download limonada.jpg "lemonade"
download agua-mineral.jpg "water-bottle"
download vino-tinto.jpg "red-wine"
download vino-blanco.jpg "white-wine"
download fernet.jpg "fernet-cocktail"
download gin-tonic.jpg "gin-tonic"
download cerveza.jpg "beer-glass"
download jugo-natural.jpg "orange-juice"

download cheesecake.jpg "cheesecake"
download helado.jpg "ice-cream"
download brownie.jpg "brownie-dessert"
download tiramisu.jpg "tiramisu"
download flan.jpg "flan-dessert"
download panqueques.jpg "crepes-dessert"
download lemon-pie.jpg "lemon-pie"
download chocotorta.jpg "chocolate-cake"
download mousse.jpg "chocolate-mousse"
download volcan-chocolate.jpg "lava-cake"
